checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['*']
build:
    environment:
        python: 3.6.2
        postgresql: false
        redis: false
    tests:
        override:
            -
                command: 'tox'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
